import {StyleSheet} from 'react-native';

export const scoreCartStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    alignContent: 'flex-start',
    justifyContent: 'space-evenly',
  },
  headerText: {
    flex: 0.05,
    fontSize: 20,
    lineHeight: 21,
    fontFamily: 'Avenir Next',
    fontWeight: '600',
  },
  subContainer: {
    flex: 0.9,
    backgroundColor: 'white',
    justifyContent: 'flex-start',
    zIndex: 2,
  },
  scoreCartContainer: {flex: 0.22, paddingBottom: '5%'},
  boardData: {
    flex: 0.1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  boardLable: {
    width: '100%',
    color: '#B5C0C8',
    fontSize: 15,
    lineHeight: 16,
    fontFamily: 'Avenir Next',
  },
  therdSection: {
    flex: 0.14,
    width: '90%',
    alignSelf: 'center',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  sectionLable: {width: '100%', height: '17%', top: 15},
  sectionLableText: {
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '600',
    color: '#727682',
    // fontFamily: 'Montserrat-Regular',
  },
  sectionButtonContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionButton: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#452C55',
    flexDirection: 'row',
  },
  sectionButtonImage: {color: '#FFFFFF', width: 15, height: 13, right: 5},
  sectionIcon: {color: '', width: 15, height: 13, right: 5},
  sectionButtonLable: {
    color: '#727682',
    fontSize: 14,
    lineHeight: 16,
    fontFamily: 'Montserrat-Regular',
  },
  progressContainer: {
    flex: 0.05,
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'space-between',
  },
  progressSubContainer: {
    width: '50%',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  progressSubContainerText: {
    color: 'gray',
    fontFamily: 'Montserrat-bold',
    fontWeight: '600',
  },
  progressLine: {
    flex: 0.05,
    width: '90%',
    alignSelf: 'center',
    top: 15,
  },
  progressLineSubContainer: {flexDirection: 'row', width: '100%'},
  leftProgressLine: {
    width: '70%',
    height: 10,
    backgroundColor: '#1E90FF',
    borderBottomLeftRadius: 25,
    borderTopLeftRadius: 25,
  },
  rightProgressLine: {
    width: '30%',
    height: 10,
    backgroundColor: '#0041C2',
    borderBottomRightRadius: 25,
    borderTopRightRadius: 25,
  },
  progressLineText: {
    // top: 15,
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  progressLineTextLable: {
    color: '#B5C0C8',
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
    fontFamily: 'Montserrat-Regular',
  },
});
